export const SAMPLE_XML = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE score-partwise PUBLIC "-//Recordare//DTD MusicXML 4.0 Partwise//EN" "http://www.musicxml.org/dtds/partwise.dtd">
<score-partwise version="4.0">
  <work>
    <work-title>Prev_258.0</work-title>
  </work>
  <identification>
    <creator type="composer">Transcribed by Oemer</creator>
  </identification>
  <part-list>
    <score-part id="P1">
      <part-name>Piano</part-name>
      <score-instrument id="P1-I1">
        <instrument-name>Piano</instrument-name>
        <instrument-sound>keyboard.piano</instrument-sound>
      </score-instrument>
      <midi-instrument id="P1-I1">
        <midi-channel>1</midi-channel>
        <midi-program>1</midi-program>
        <volume>80</volume>
        <pan>0</pan>
      </midi-instrument>
    </score-part>
  </part-list>
  <part id="P1">
    <sound tempo="90"/>
    <measure number="1">
      <attributes>
        <divisions>16</divisions>
        <key>
          <fifths>0</fifths>
        </key>
        <staves>2</staves>
        <clef number="1">
          <sign>G</sign>
          <line>2</line>
        </clef>
        <clef number="2">
          <sign>F</sign>
          <line>4</line>
        </clef>
      </attributes>
      <note>
        <rest measure="yes"/>
        <duration>8</duration>
        <staff>2</staff>
      </note>
      <backup>
        <duration>8</duration>
      </backup>
      <note>
        <pitch>
          <step>B</step>
          <alter>0</alter>
          <octave>4</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>1</staff>
        <voice>1</voice>
      </note>
    </measure>
    <measure number="2">
      <note>
        <pitch>
          <step>G</step>
          <alter>0</alter>
          <octave>5</octave>
        </pitch>
        <duration>24</duration>
        <type>quarter</type>
        <dot/>
        <stem>down</stem>
        <staff>1</staff>
        <voice>1</voice>
      </note>
      <backup>
        <duration>24</duration>
      </backup>
      <note>
        <pitch>
          <step>E</step>
          <alter>0</alter>
          <octave>2</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <pitch>
          <step>G</step>
          <alter>0</alter>
          <octave>3</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <chord/>
        <pitch>
          <step>E</step>
          <alter>0</alter>
          <octave>4</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <pitch>
          <step>B</step>
          <alter>0</alter>
          <octave>3</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <chord/>
        <pitch>
          <step>G</step>
          <alter>0</alter>
          <octave>4</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <chord/>
        <pitch>
          <step>E</step>
          <alter>0</alter>
          <octave>4</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <pitch>
          <step>E</step>
          <alter>0</alter>
          <octave>3</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <backup>
        <duration>8</duration>
      </backup>
      <note>
        <pitch>
          <step>G</step>
          <alter>0</alter>
          <octave>5</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>1</staff>
        <voice>1</voice>
      </note>
      <note>
        <pitch>
          <step>F</step>
          <alter>0</alter>
          <octave>5</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>1</staff>
        <voice>1</voice>
      </note>
      <backup>
        <duration>8</duration>
      </backup>
      <note>
        <pitch>
          <step>A</step>
          <alter>0</alter>
          <octave>3</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <chord/>
        <pitch>
          <step>D</step>
          <alter>0</alter>
          <octave>4</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <pitch>
          <step>A</step>
          <alter>0</alter>
          <octave>4</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <chord/>
        <pitch>
          <step>C</step>
          <alter>0</alter>
          <octave>4</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <chord/>
        <pitch>
          <step>D</step>
          <alter>0</alter>
          <octave>4</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <backup>
        <duration>8</duration>
      </backup>
      <note>
        <pitch>
          <step>G</step>
          <alter>0</alter>
          <octave>5</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>1</staff>
        <voice>1</voice>
      </note>
      <note>
        <pitch>
          <step>E</step>
          <alter>0</alter>
          <octave>2</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <backup>
        <duration>8</duration>
      </backup>
      <note>
        <pitch>
          <step>F</step>
          <alter>0</alter>
          <octave>5</octave>
        </pitch>
        <duration>24</duration>
        <type>quarter</type>
        <dot/>
        <stem>down</stem>
        <staff>1</staff>
        <voice>1</voice>
      </note>
      <backup>
        <duration>16</duration>
      </backup>
      <note>
        <pitch>
          <step>G</step>
          <alter>0</alter>
          <octave>3</octave>
        </pitch>
        <duration>16</duration>
        <type>quarter</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <chord/>
        <pitch>
          <step>E</step>
          <alter>0</alter>
          <octave>4</octave>
        </pitch>
        <duration>16</duration>
        <type>quarter</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <pitch>
          <step>B</step>
          <alter>0</alter>
          <octave>3</octave>
        </pitch>
        <duration>16</duration>
        <type>quarter</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <chord/>
        <pitch>
          <step>E</step>
          <alter>0</alter>
          <octave>4</octave>
        </pitch>
        <duration>16</duration>
        <type>quarter</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <chord/>
        <pitch>
          <step>G</step>
          <alter>0</alter>
          <octave>4</octave>
        </pitch>
        <duration>16</duration>
        <type>quarter</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <backup>
        <duration>16</duration>
      </backup>
      <note>
        <rest measure="yes"/>
        <duration>16</duration>
        <staff>1</staff>
      </note>
      <note>
        <pitch>
          <step>E</step>
          <alter>0</alter>
          <octave>5</octave>
        </pitch>
        <duration>16</duration>
        <type>quarter</type>
        <stem>down</stem>
        <staff>1</staff>
        <voice>1</voice>
      </note>
      <backup>
        <duration>16</duration>
      </backup>
      <note>
        <pitch>
          <step>D</step>
          <alter>0</alter>
          <octave>2</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <pitch>
          <step>G</step>
          <alter>0</alter>
          <octave>3</octave>
        </pitch>
        <duration>16</duration>
        <type>quarter</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <chord/>
        <pitch>
          <step>E</step>
          <alter>0</alter>
          <octave>4</octave>
        </pitch>
        <duration>16</duration>
        <type>quarter</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <backup>
        <duration>16</duration>
      </backup>
      <note>
        <rest measure="yes"/>
        <duration>8</duration>
        <staff>1</staff>
      </note>
      <note>
        <pitch>
          <step>B</step>
          <alter>0</alter>
          <octave>3</octave>
        </pitch>
        <duration>16</duration>
        <type>quarter</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <chord/>
        <pitch>
          <step>G</step>
          <alter>0</alter>
          <octave>4</octave>
        </pitch>
        <duration>16</duration>
        <type>quarter</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <note>
        <chord/>
        <pitch>
          <step>E</step>
          <alter>0</alter>
          <octave>4</octave>
        </pitch>
        <duration>16</duration>
        <type>quarter</type>
        <stem>down</stem>
        <staff>2</staff>
        <voice>1</voice>
      </note>
      <backup>
        <duration>16</duration>
      </backup>
      <note>
        <pitch>
          <step>B</step>
          <alter>0</alter>
          <octave>4</octave>
        </pitch>
        <duration>8</duration>
        <type>eighth</type>
        <stem>down</stem>
        <staff>1</staff>
        <voice>1</voice>
      </note>
    </measure>
</score-partwise>`;