import React, { useRef, useCallback, useState } from 'react';
import { GuqinNote } from '../types';
import { JianzipuChar } from './JianzipuChar';
import { Download, Loader2, Printer } from 'lucide-react';
import { toPng } from 'html-to-image';

interface Props {
  notes: GuqinNote[];
}

export const ScoreViewer: React.FC<Props> = ({ notes }) => {
  const scoreRef = useRef<HTMLDivElement>(null);
  const [isDownloading, setIsDownloading] = useState(false);

  const handleDownload = useCallback(async () => {
    if (scoreRef.current === null) {
      return;
    }

    setIsDownloading(true);
    try {
      await new Promise(resolve => setTimeout(resolve, 100));

      const dataUrl = await toPng(scoreRef.current, { 
        cacheBust: true, 
        backgroundColor: '#faf9f6', // Match the paper color
        pixelRatio: 2 
      });
      
      const link = document.createElement('a');
      link.download = 'guqin-score.png';
      link.href = dataUrl;
      link.click();
    } catch (err) {
      console.error('Failed to generate image', err);
      alert('Could not generate image. Please try again.');
    } finally {
      setIsDownloading(false);
    }
  }, [scoreRef]);

  if (notes.length === 0) {
    return (
      <div className="h-full flex flex-col items-center justify-center text-stone-400 font-serif">
        <div className="w-24 h-24 mb-6 opacity-20 border-4 border-stone-400 rounded-full flex items-center justify-center">
             <span className="text-4xl">琴</span>
        </div>
        <p className="text-lg tracking-widest text-stone-500">AWAITING SCORE</p>
        <p className="text-sm opacity-60 mt-2">Please upload a MusicXML file</p>
      </div>
    );
  }

  return (
    <div className="relative flex flex-col items-center min-h-full">
      
      {/* Action Bar (Floating) */}
      <div className="sticky top-0 z-50 mb-6 flex gap-3">
        <button 
          onClick={handleDownload}
          disabled={isDownloading}
          className="flex items-center gap-2 px-5 py-2.5 bg-stone-900 text-stone-50 rounded shadow-xl hover:bg-amber-900 hover:-translate-y-0.5 transition-all text-xs uppercase tracking-widest font-semibold disabled:opacity-70 disabled:cursor-not-allowed disabled:transform-none"
        >
          {isDownloading ? <Loader2 className="w-4 h-4 animate-spin" /> : <Download className="w-4 h-4" />}
          {isDownloading ? 'Inking...' : 'Export PNG'}
        </button>
      </div>

      {/* The Paper Sheet */}
      <div 
        ref={scoreRef} 
        className="relative w-full max-w-[1100px] min-h-[1200px] bg-[#faf9f6] shadow-2xl mb-20 p-16 print:shadow-none"
        style={{
             backgroundImage: 'linear-gradient(#e5e7eb 1px, transparent 1px), linear-gradient(90deg, #e5e7eb 1px, transparent 1px)',
             backgroundSize: '100% 100px', // Subtle vertical guide hints
             backgroundPosition: '0 0, 0 0'
        }}
      >
        {/* Paper Texture Overlay (Optional, simplified with color) */}
        
        {/* Header */}
        <div className="relative flex flex-col items-center mb-16 border-b-2 border-stone-800 pb-8">
          
          {/* Decorative Seal (CSS based) */}
          <div className="absolute right-0 top-0 w-12 h-12 border-2 border-red-800 rounded-sm flex items-center justify-center opacity-80 rotate-12 transform translate-x-4 -translate-y-2">
              <span className="text-red-800 text-xs font-bold leading-none writing-vertical-rl">古琴<br/>新譜</span>
          </div>

          <h2 className="text-5xl font-bold text-stone-900 tracking-[0.3em] mb-4 scale-y-110">
            古琴減字譜
          </h2>
          <div className="flex items-center gap-4 text-stone-500 text-sm tracking-[0.2em] uppercase">
             <span>Traditional Guqin Notation</span>
             <span className="w-1 h-1 bg-stone-400 rounded-full"></span>
             <span>Num. Notation</span>
          </div>
        </div>
        
        {/* Score Body - Grid Layout */}
        <div className="flex flex-wrap gap-y-12 gap-x-10 justify-start content-start min-h-[600px] px-8">
          {notes.map((note, index) => (
             <JianzipuChar key={index} note={note} />
          ))}
        </div>
        
        {/* Footer */}
        <div className="mt-20 pt-6 border-t border-stone-300 flex justify-between items-end text-stone-400">
            <div className="text-xs uppercase tracking-widest">
                Generated by Guqinize
            </div>
            <div className="text-right">
                <p className="text-xs font-serif italic">Standard Tuning &middot; C Major / A Minor Interpretation</p>
            </div>
        </div>

      </div>
    </div>
  );
};